import pg from "pg";
import { BASE, assert, expectVisible, launch, login, section, setPage, step, summary, until } from "./h.mjs";

const db = new pg.Client({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
await db.connect();
const q = async (s, p) => (await db.query(s, p)).rows;
const { browser, page, errors } = await launch();
setPage(page);
const toast = (t) => page.getByText(t, { exact: false }).first();
const dialog = () => page.getByRole("dialog");
const pub = async (path) => (await page.request.get(BASE + path)).status();
const pubHtml = async (path) => (await page.request.get(BASE + path)).text();
await q(`delete from employees where full_name like 'Especialista E2E%'`);
await login(page, "tmp-admin@glow.test");

section("Productos y venta rápida");
await step("Productos: crear, editar precio y verlo en la lista", async () => {
  await page.goto(BASE + "/admin/services?tab=productos");
  await page.getByRole("button", { name: "+ Nuevo producto" }).click();
  await page.locator("#pr-n").fill("Shampoo E2E");
  await page.locator("#pr-p").fill("500");
  await dialog().getByRole("button", { name: "Guardar" }).click();
  await expectVisible(toast("Producto guardado"), "toast", 10000);
  await expectVisible(page.getByRole("cell", { name: "Shampoo E2E" }), "fila del producto");
  await page.locator("tr", { hasText: "Shampoo E2E" }).getByRole("button", { name: "Editar" }).click();
  await page.locator("#pr-p").fill("550");
  await dialog().getByRole("button", { name: "Guardar" }).click();
  await expectVisible(toast("Producto guardado"), "toast edición", 10000);
  await until(async () => Number((await q(`select price from products where name='Shampoo E2E'`))[0].price) === 550, "el precio del producto pasa a 550");
});
await step("Venta rápida: producto + concepto libre, pago total → recibo", async () => {
  await page.goto(BASE + "/admin/sales");
  await page.getByRole("button", { name: "+ Nueva venta" }).click();
  await page.locator("#qs-prod").selectOption({ label: "Shampoo E2E — RD$ 550" });
  await page.locator("#qs-cn").fill("Servicio libre E2E");
  await page.locator("#qs-cp").fill("200");
  await dialog().getByRole("button", { name: "Agregar", exact: true }).click();
  await page.getByRole("button", { name: /Pagar todo/ }).click();
  await dialog().getByRole("button", { name: /Registrar venta y cobrar RD\$ 750/ }).click();
  await page.waitForURL("**/admin/sales/**", { timeout: 15000 });
  await expectVisible(page.getByText("Shampoo E2E"), "línea del recibo");
  await expectVisible(page.getByText("Mostrador"), "venta sin cliente");
  const [s] = await q(`select s.total, s.payment_status, (select count(*) from sale_items where sale_id=s.id)::int items from sales s where s.id=$1`, [page.url().split("/").pop()]);
  assert(Number(s.total) === 750 && s.payment_status === "pagado" && s.items === 2, JSON.stringify(s));
});
await step("Venta rápida: no deja registrar sin artículos ni con descuento mayor al subtotal", async () => {
  await page.goto(BASE + "/admin/sales");
  await page.getByRole("button", { name: "+ Nueva venta" }).click();
  assert(await dialog().getByRole("button", { name: /Registrar venta/ }).isDisabled(), "debe estar deshabilitado sin artículos");
  await page.locator("#qs-cn").fill("X"); await page.locator("#qs-cp").fill("100");
  await dialog().getByRole("button", { name: "Agregar", exact: true }).click();
  await page.locator("#qs-d").fill("500");
  await dialog().getByRole("button", { name: /Registrar venta/ }).click();
  await expectVisible(dialog().getByText(/descuento no puede superar/i), "error de descuento");
  await page.keyboard.press("Escape");
});

section("Servicios, categorías y la web pública (purga inmediata)");
await step("Crear servicio con variante, complemento y especialista", async () => {
  await page.goto(BASE + "/admin/services/new");
  await page.locator("#s-name").fill("Servicio E2E");
  await page.locator("#s-cat").selectOption({ label: "Uñas" });
  await page.locator("#s-short").fill("Servicio de prueba automática");
  await page.locator("#s-price").fill("800");
  await page.locator("#s-dur").fill("50");
  await page.getByRole("button", { name: "+ Variante" }).click();
  await page.getByLabel("Nombre de la variante").fill("Corto");
  await page.getByLabel("Precio de la variante").fill("700");
  await page.getByLabel("Duración de la variante").fill("40");
  await page.getByRole("button", { name: "+ Complemento" }).click();
  await page.getByLabel("Nombre del complemento").fill("Extra E2E");
  await page.getByLabel("Precio adicional").fill("100");
  await page.getByLabel("Minutos adicionales").fill("10");
  await page.getByLabel("Ana (demo)").check();
  await page.getByRole("button", { name: "Guardar servicio" }).click();
  await expectVisible(toast("Servicio guardado"), "toast", 12000);
  await page.waitForURL(/\/admin\/services\/[0-9a-f-]{36}$/, { timeout: 12000 });
  const [s] = await q(`select s.slug, s.active, (select count(*) from service_variants where service_id=s.id)::int v, (select count(*) from service_addons where service_id=s.id)::int a, (select count(*) from employee_services where service_id=s.id)::int e from services s where name='Servicio E2E'`);
  assert(s.slug === "servicio-e2e" && s.v === 1 && s.a === 1 && s.e === 1 && s.active, JSON.stringify(s));
});
await step("El servicio nuevo aparece en la web al instante (sin esperar la caché)", async () => {
  assert((await pub("/services/servicio-e2e")) === 200, "la página del servicio debe existir");
  assert((await pubHtml("/services")).includes("Servicio E2E"), "debe aparecer en el listado");
});
await step("Desactivarlo lo retira de la web al instante", async () => {
  await page.goto(BASE + "/admin/services");
  await page.locator("tr", { hasText: "Servicio E2E" }).getByRole("button", { name: "Desactivar" }).click();
  await expectVisible(toast("Servicio desactivado"), "toast", 10000);
  assert((await pub("/services/servicio-e2e")) === 404, "debe dar 404 al instante");
  assert(!(await pubHtml("/services")).includes("Servicio E2E"), "no debe verse en el listado");
  await page.locator("tr", { hasText: "Servicio E2E" }).getByRole("button", { name: "Activar" }).click();
  await expectVisible(toast("Servicio activado"), "reactivado", 10000);
  assert((await pub("/services/servicio-e2e")) === 200, "vuelve a publicarse");
});
await step("Editar precio y nombre del especialista asignado", async () => {
  const [{ id }] = await q(`select id from services where name='Servicio E2E'`);
  await page.goto(`${BASE}/admin/services/${id}`);
  await page.locator("#s-price").fill("850");
  await page.getByRole("button", { name: "Guardar servicio" }).click();
  await expectVisible(toast("Servicio guardado"), "toast", 12000);
  assert(Number((await q(`select price from services where id=$1`, [id]))[0].price) === 850, "precio");
});
await step("Duplicar crea una copia inactiva y Eliminar borra un servicio sin historial", async () => {
  await page.goto(BASE + "/admin/services");
  await page.locator("tr", { hasText: "Servicio E2E" }).getByRole("button", { name: "Duplicar" }).click();
  await page.waitForURL(/\/admin\/services\/[0-9a-f-]{36}$/, { timeout: 12000 });
  const [c] = await q(`select active, name from services where name='Servicio E2E (copia)'`);
  assert(c && c.active === false, "la copia debe quedar inactiva");
  await page.getByRole("button", { name: "Eliminar", exact: true }).click();
  await dialog().getByRole("button", { name: "Eliminar" }).click();
  await expectVisible(toast("Servicio eliminado"), "toast", 12000);
  assert((await q(`select count(*)::int c from services where name='Servicio E2E (copia)'`))[0].c === 0, "la copia debe borrarse");
});
await step("Eliminar un servicio con historial lo ARCHIVA (no se pierde el reporte)", async () => {
  const [{ id }] = await q(`select id from services where name='Servicio E2E'`);
  const [e] = await q(`select id from employees where full_name like 'Ana%'`);
  await q(`select create_booking(jsonb_build_object('first_name','Hist','last_name','E2E','phone','8295557210','status','confirmado','start_time',$1::text,'employee_id',$2::text,'services',jsonb_build_array(jsonb_build_object('service_id',$3::text,'variant_id',(select id from service_variants where service_id=$3::uuid limit 1)))))`, [new Date(Date.now() + 9 * 864e5).toISOString(), e.id, id]);
  await page.goto(`${BASE}/admin/services/${id}`);
  await page.getByRole("button", { name: "Eliminar", exact: true }).click();
  await dialog().getByRole("button", { name: "Eliminar" }).click();
  await expectVisible(toast("quedó archivado"), "aviso de archivado", 12000);
  const [s] = await q(`select active from services where id=$1`, [id]);
  assert(s && s.active === false, "debe seguir existiendo, inactivo");
});
await step("Categorías: crear, editar, no eliminar si tiene servicios, eliminar vacía", async () => {
  await page.goto(BASE + "/admin/services?tab=categorias");
  await page.getByRole("button", { name: "+ Nueva categoría" }).click();
  await page.locator("#cat-n").fill("Categoría E2E");
  await page.locator("#cat-d").fill("Solo para pruebas");
  await dialog().getByRole("button", { name: "Guardar" }).click();
  await expectVisible(toast("Categoría guardada"), "toast", 10000);
  await page.locator("article", { hasText: "Categoría E2E" }).getByRole("button", { name: "Editar" }).click();
  await page.locator("#cat-n").fill("Categoría E2E editada");
  await dialog().getByRole("button", { name: "Guardar" }).click();
  await expectVisible(page.getByRole("heading", { name: "Categoría E2E editada" }), "renombrada");
  await page.locator("article", { hasText: "Uñas" }).getByRole("button", { name: "Eliminar" }).click();
  await dialog().getByRole("button", { name: "Eliminar" }).click();
  await expectVisible(toast("tiene"), "bloqueo por tener servicios", 10000);
  await page.locator("article", { hasText: "Categoría E2E editada" }).getByRole("button", { name: "Eliminar" }).click();
  await dialog().getByRole("button", { name: "Eliminar" }).click();
  await expectVisible(toast("Categoría eliminada"), "toast", 10000);
  assert((await q(`select count(*)::int c from service_categories where name like 'Categoría E2E%'`))[0].c === 0, "no se borró");
});

section("Especialistas");
await step("Crear especialista con servicios, horario semanal y ausencia", async () => {
  await page.goto(BASE + "/admin/staff/new");
  await page.locator("#e-name").fill("Especialista E2E");
  await page.locator("#e-spec").fill("Pruebas");
  await page.getByLabel("Manicure", { exact: true }).check();
  await page.getByRole("button", { name: "Guardar" }).click();
  await expectVisible(toast("Especialista guardado"), "toast", 12000);
  await page.waitForURL(/\/admin\/staff\/[0-9a-f-]{36}$/, { timeout: 12000 });
  await page.getByLabel("Lunes", { exact: false }).first().check();
  await page.getByRole("button", { name: "Guardar horario" }).click();
  await expectVisible(toast("Horario guardado"), "horario", 10000);
  const [{ id }] = await q(`select id from employees where full_name='Especialista E2E'`);
  assert((await q(`select count(*)::int c from employee_schedules where employee_id=$1`, [id]))[0].c === 1, "horario");
  const d1 = new Date(Date.now() + 20 * 864e5).toISOString().slice(0, 10);
  await page.locator("#to-a").fill(`${d1}T09:00`); await page.locator("#to-b").fill(`${d1}T18:00`); await page.locator("#to-r").fill("Vacaciones E2E");
  await page.getByRole("button", { name: "Agregar ausencia" }).click();
  await expectVisible(toast("Ausencia registrada"), "ausencia", 10000);
  await page.getByRole("button", { name: "Quitar" }).first().click();
  await page.waitForTimeout(1200);
  assert((await q(`select count(*)::int c from employee_time_off where employee_id=$1`, [id]))[0].c === 0, "la ausencia debe quitarse");
});
await step("Aparece en la web y se puede reordenar; al eliminar (sin historial) desaparece", async () => {
  assert((await pubHtml("/about")).includes("Especialista E2E"), "debe verse en Nosotros al instante");
  const order = async () => (await q(`select full_name from employees order by display_order, full_name`)).map((r) => r.full_name);
  const before = await order();
  const last = before.at(-1), prev = before.at(-2);
  await page.goto(BASE + "/admin/staff");
  await page.waitForLoadState("networkidle");
  await page.getByRole("button", { name: `Subir ${last}` }).click();
  await until(async () => (await order()).at(-2) === last, "el especialista sube un lugar");
  await page.reload();
  await page.getByRole("button", { name: `Subir ${prev}` }).click();
  await until(async () => (await order()).join("|") === before.join("|"), "el orden original se restablece");
  const [{ id }] = await q(`select id from employees where full_name='Especialista E2E'`);
  await page.goto(`${BASE}/admin/staff/${id}`);
  await page.getByRole("button", { name: "Eliminar", exact: true }).click();
  await dialog().getByRole("button", { name: "Eliminar" }).click();
  await expectVisible(toast("Especialista eliminado"), "toast", 12000);
  assert((await q(`select count(*)::int c from employees where full_name='Especialista E2E'`))[0].c === 0, "debe borrarse");
  assert(!(await pubHtml("/about")).includes("Especialista E2E"), "debe salir de la web al instante");
});

section("Clientes");
await step("Crear, editar, notas, desactivar/activar", async () => {
  await page.goto(BASE + "/admin/clients");
  await page.getByRole("button", { name: "+ Nuevo cliente" }).click();
  await page.locator("#c-fn").fill("E2E"); await page.locator("#c-ln").fill("Principal"); await page.locator("#c-ph").fill("829-555-7202");
  await dialog().getByRole("button", { name: "Guardar" }).click();
  await page.waitForURL(/\/admin\/clients\/[0-9a-f-]{36}$/, { timeout: 12000 });
  await page.getByLabel("Notas privadas").fill("Prefiere uñas cortas");
  await page.getByRole("button", { name: "Guardar notas" }).click();
  await expectVisible(toast("Notas guardadas"), "notas", 10000);
  await page.getByRole("button", { name: "Desactivar" }).click();
  await expectVisible(toast("Cliente desactivado"), "desactivado", 10000);
  await page.getByRole("button", { name: "Activar" }).click();
  await expectVisible(toast("Cliente activado"), "activado", 10000);
  const [c] = await q(`select internal_notes, active from clients where phone_normalized='8295557202'`);
  assert(c.internal_notes === "Prefiere uñas cortas" && c.active === true, JSON.stringify(c));
});
await step("Teléfono repetido se rechaza con mensaje claro", async () => {
  await page.goto(BASE + "/admin/clients");
  await page.getByRole("button", { name: "+ Nuevo cliente" }).click();
  await page.locator("#c-fn").fill("Otro"); await page.locator("#c-ph").fill("+1 (829) 555-7202");
  await dialog().getByRole("button", { name: "Guardar" }).click();
  await expectVisible(dialog().getByText(/Ya existe un cliente con ese teléfono/), "mensaje de duplicado");
  await page.keyboard.press("Escape");
});
await step("Fusionar un duplicado traslada su historial y lo elimina", async () => {
  const dup = (await q(`select create_booking(jsonb_build_object('first_name','E2E','last_name','Duplicado','phone','8295557203','start_time',$1::text,'services',jsonb_build_array(jsonb_build_object('service_id',(select id from services where slug='manicure'))))) r`, [new Date(Date.now() + 12 * 864e5).toISOString()]))[0].r;
  const [{ id }] = await q(`select id from clients where phone_normalized='8295557202'`);
  await page.goto(`${BASE}/admin/clients/${id}`);
  await page.getByRole("button", { name: "Fusionar duplicado" }).click();
  await page.locator("#mg-q").fill("E2E Duplicado");
  await dialog().getByRole("button", { name: /E2E Duplicado/ }).click();
  await dialog().getByRole("button", { name: "Fusionar", exact: true }).click();
  await expectVisible(toast("Clientes fusionados"), "toast", 12000);
  assert((await q(`select count(*)::int c from clients where phone_normalized='8295557203'`))[0].c === 0, "el duplicado debe desaparecer");
  assert((await q(`select count(*)::int c from appointments where client_id=$1`, [id]))[0].c === 1, "la cita debe pasar al cliente principal");
  assert(dup.id, "ok");
});
await step("Eliminar: bloqueado con historial; permitido sin historial", async () => {
  const [{ id }] = await q(`select id from clients where phone_normalized='8295557202'`);
  await page.goto(`${BASE}/admin/clients/${id}`);
  await page.getByRole("button", { name: "Eliminar", exact: true }).click();
  await dialog().getByRole("button", { name: "Eliminar" }).click();
  await expectVisible(toast("cita(s)"), "bloqueo por historial", 10000);
  await q(`delete from appointments where client_id=$1`, [id]);
  await page.goto(`${BASE}/admin/clients/${id}`);
  await page.getByRole("button", { name: "Eliminar", exact: true }).click();
  await dialog().getByRole("button", { name: "Eliminar" }).click();
  await expectVisible(toast("Cliente eliminado"), "toast", 12000);
  assert((await q(`select count(*)::int c from clients where id=$1`, [id]))[0].c === 0, "debe borrarse");
});

console.log("\nLimpieza de datos de prueba…");
await q(`delete from payments where sale_id in (select id from sales where notes is null and client_id is null and created_at > now() - interval '1 hour' and total=750)`);
await q(`delete from sale_items where sale_id in (select id from sales where client_id is null and total=750)`);
await q(`delete from sales where client_id is null and total=750`);
await q(`delete from products where name='Shampoo E2E'`);
await q(`delete from appointments where client_id in (select id from clients where phone_normalized in ('8295557210','8295557202','8295557203'))`);
await q(`delete from clients where phone_normalized in ('8295557210','8295557202','8295557203')`);
await q(`delete from services where name like 'Servicio E2E%'`);
await q(`delete from employees where full_name like 'Especialista E2E%'`);
await db.end();
const code = summary(errors);
await browser.close();
process.exit(code);
